import openai
import time
import random

# Replace 'YOUR_API_KEY' with your actual OpenAI API key
api_key = 'YOUR_API_KEY'

# Initialize the OpenAI API client
openai.api_key = api_key

# List of ML topics and corresponding prompts
ml_topics = [
    {
        "topic": "Linear Regression",
        "prompt": "Explain the concept of linear regression in machine learning."
    },
    {
        "topic": "Decision Trees",
        "prompt": "What are decision trees and how do they work in classification problems?"
    },
    {
        "topic": "Neural Networks",
        "prompt": "Describe the architecture and components of a neural network."
    },
        {
        "topic": "Support Vector Machines",
        "prompt": "Explain the principles behind Support Vector Machines (SVMs) in machine learning."
    },
    {
        "topic": "Random Forests",
        "prompt": "What are Random Forests, and how do they address overfitting in decision trees?"
    },
    # Add more topics and prompts as needed
]
# Number of requests allowed per minute
requests_per_minute = 3

# Function to ask a question and wait for user input
def ask_question(prompt):
    try:
        # Make an API call
        response = openai.Completion.create(
            engine="text-davinci-002",  # Choose an appropriate engine
            prompt=prompt,
            max_tokens=500  # Adjust based on your needs
        )

        # Print the question generated by the AI tutor
        print(f"AI Tutor: {response.choices[0].text}\n")

        # Wait for user input
        input("Press Enter to continue...")

    except Exception as e:
        print(f"Error: {str(e)}")

# Function to answer user doubts or questions
def answer_doubts():
    while True:
        user_input = input("Enter doubt or type 'Quit' to exit: ")

        if user_input.lower() == 'quit':
            break

        # Ask the AI tutor for an answer
        ask_question(user_input)

# Loop through ML topics and teach them
for topic_info in ml_topics:
    topic = topic_info["topic"]
    prompt = topic_info["prompt"]

    print(f"Topic: {topic}")
    print("AI Tutor: Let's learn about this topic.\n")

    # Ask a question related to the topic
    ask_question(prompt)

    # Ask if the user wants to ask doubts or learn another topic
    choice = input("Any Doubts or Continue with next topic (Doubts/Yes/No)?: ")

    if choice.lower() == "doubts":
        # Allow the user to ask doubts
        answer_doubts()
    elif choice.lower() != "yes":
        break

print("AI Tutor: That's all for today. Feel free to come back anytime to learn more or ask questions!")
